### ISSUE TITLE
PDF not working

### ISSUE THREAD

**Issue by messschuh** [GadgetAngel/SKR-PRO-V1.1-Stepper-Driver-Jumper-Configuration-Manual#1]
https://github.com/GadgetAngel/SKR-PRO-V1.1-Stepper-Driver-Jumper-Configuration-Manual/blob/master/CURRENT-Manual/SKR%20PRO%20V1.1%20Stepper%20Driver%20Jumper%20Configuration_version%20V3.8.pdf
<img width="1023" alt="Bildschirmfoto 2020-05-03 um 17 39 18" src="https://user-images.githubusercontent.com/40902969/80918447-465dff00-8d65-11ea-9516-7d2a6d9eef46.png">

download/cloning  is also not working it breaks with error.

**Comment by GadgetAngel** [comment]
Sorry about that I needed to purchase a data plan.  If you have any other additional trouble please let me know
